import {
  Testimonial,
  Mentor,
  BlogPost,
  Metric,
  InternProject,
  Cohort,
  Partner,
  Resource,
} from "./types";
import williams from "./../public/images/team/Williams.jpg";
import timi from "./../public/images/team/Photo - Timilehin Abegunde.png";
import akanimo from "./../public/images/team/ak.png";
import wangui from "./../public/images/team/Wangui.jpg";
import chioma from "./../public/interns images/chioma-favour-paul-chike-.jpeg"
import seun from "./../public/images/team/bamgbade.jpg";
import Aminat from "./../public/interns images/aminat-bankole.jpeg";
import BSY from "./../public/images/team/BSY.jpg";
import Christabel from "./../public/interns images/1757934584213 - Christabel Nzekwe.jpg";
import Faith from "./../public/interns images/20240920_163231 - Faith Kolade.jpg";
// import Mattia from "./../public/interns images/20250724_103912 - Mattia Lavai.jpg";
import Adeola from "./../public/interns images/20250906_181856 - Omomowo Adeola.png";
import Aishat from "./../public/interns images/IMG_4700 - Aishat Yusuf.jpeg";
import Emmanuel from "./../public/interns images/IMG-20250422-WA0056 - Emmanuel Adeleke.jpg";
import Tosin from "./../public/interns images/IMG_9952 - Tosin Oyedun.jpeg";
import Evelyn from "./../public/interns images/IMG_2540 - Evelyn Nyorelagos.jpeg";
import Sifan from "./../public/interns images/Sifan - Sifan Yemane.jpg";
import Olawale from "./../public/interns images/20250911_103843 - Olowolayemo Olawale.jpg";
import Janet from "./../public/interns images/Screenshot_20250905-034700~2 - AFEHOMO JANET.png";
import Olayele from "./../public/interns images/My Picture New 1 - olaleye ifeoluwa.png";
import Esther from "./../public/interns images/IMG_20200419_151340_1_1663943858802 - ESTHER FAMAKINWA.jpg";
import Musa from "./../public/interns images/IMG-20230911-WA0077 - Musa Saidu Auna.jpg";
import John from "./../public/interns images/JPEG_20250722_172756_7105081795096905677 - Ibhaluobe Eichie.jpg";
// import Waheed from "./../public/interns images/Screenshot_20250430-214002 - waheed sodiq.jpg";
import Adefemi from "./../public/interns images/FB_IMG_1752996434061 - ADEDAMOLA ADEFEMI.jpg";
import Samuel from "./../public/interns images/Profile picture - Samuel Adewale.jpg";
import SAMUEL from "./../public/interns images/tmp_6d65ad58-4ff7-40f9-bcdd-403de5ad481d - SAMUEL DANIA.jpeg"
import Emem from "./../public/interns images/Emem-Peace.jpg";
import Taiwo from "./../public/interns images/Taiwo_Oyewale.jpg";
import Victor from "./../public/interns images/Victor-udo.jpeg";
import Gideon from "./../public/interns images/gideon.webp";
import Ayiro from "./../public/interns images/Ariyo_O.B.png";
import Adejayan from "./../public/interns images/file_000000003f6061f9b2ab5e9092cce116 - Esther Adejayan (X-star).png"

export const testimonials: Testimonial[] = [
  {
    id: "1",
    name: "Eduoku Emem Okon",
    role: "Frontend Developer Intern",
    country: "Nigeria",
    countryFlag: "ng",
    image: Emem,
    linkedin: "https://www.linkedin.com/in/emem-eduoku/",
    text: "iSentry Internship transformed my career. I went from tutorial hell to building real products used by actual users. The mentorship was phenomenal.",
    year: "2024",
    cohort: "2024-Q1",
  },
  {
    id: "2",
    name: "Taiwo Saidat Oyewale",
    role: "Frontend Developer Intern",
    country: "Nigeria",
    countryFlag: "ng",
    image: Taiwo,
    linkedin: "https://www.linkedin.com/in/taiwo-oyewale199/",
    text: "Working on live projects taught me more in 3 months than years of solo learning. I now work as a junior developer at a tech startup.",
    year: "2024",
    cohort: "2024-Q1",
  },
  {
    id: "3",
    name: "Wangui Njoroge",
    role: "Frontend Developer Intern",
    country: "Kenya",
    countryFlag: "ke",
    image: wangui,
    linkedin: "https://www.linkedin.com/in/wangui-njoroge-639378181/",
    text: "The collaborative environment and real-world challenges pushed me beyond my comfort zone. I gained confidence and skills I never thought possible.",
    year: "2024",
    cohort: "2024-Q2",
  },
  {
    id: "4",
    name: "Victor John Udo",
    role: "QA Engineering Intern",
    country: "Nigeria",
    countryFlag: "ng",
    image: Victor,
    linkedin: "https://www.linkedin.com/in/victorudo/",
    text: "iSentry gave me the opportunity to work with modern technologies and best practices. The experience was invaluable for my career growth.",
    year: "2024",
    cohort: "2024-Q2",
  },
  {
    id: "5",
    name: "Gideon Sunday",
    role: "Product Manager",
    country: "Nigeria",
    countryFlag: "ng",
    image: Gideon,
    linkedin: "https://www.linkedin.com/in/gideon-sunday/",
    text: "The real-world experience here is unmatched. I learned more about system design and scalability than I ever could from online courses.",
    year: "2024",
    cohort: "2024-Q1",
  },
  {
    id: "6",
    name: "Ayiro Oluwadamilola B",
    role: "Product Manager",
    country: "Nigeria",
    countryFlag: "ng",
    image: Ayiro,
    linkedin: "https://www.linkedin.com/in/ariyo-oluwadamilola/",
    text: "iSentry gave me industry connections that helped me land my first job. The network of mentors and peers is invaluable.",
    year: "2024",
    cohort: "2024-Q2",
  },
  {
    id: "7",
    name: "Nzekwe Christabel ",
    role: "Data Analysis",
    country: "Nigeria",
    countryFlag: "ng",
    image: Christabel,
    linkedin: "https://www.linkedin.com/in/christabel-nzekwe-999643176",
    text: "iSentry gave me industry connections that helped me land my first job. The network of mentors and peers is invaluable.",
    year: "2025",
    cohort: "2025-Q2",
  },
  {
    id: "8",
    name: "Janet Afehomo",
    role: "Social Media/Content Marketing",
    country: "Nigeria",
    countryFlag: "ng",
    image: Janet,
    linkedin:
      "https://www.linkedin.com/in/janet-afehomo-453a4a1b3",
    text: "iSentry gave me industry connections that helped me land my first job. The network of mentors and peers is invaluable.",
    year: "2025",
    cohort: "2025-Q2",
  },
  {
    id: "9",
    name: "Samuel Adewale ",
    role: "Product Designer",
    country: "Nigeria",
    countryFlag: "ng",
    image: Samuel,
    linkedin: "http://www.linkedin.com/in/samuel-adewale-04716921b",
    text: "iSentry gave me industry connections that helped me land my first job. The network of mentors and peers is invaluable.",
    year: "2025",
    cohort: "2025-Q2",
    isBestInCohort: true,
  },
  {
    id: "10",
    name: "Agnes Ekong ",
    role: "Social Media/Content Marketing",
    country: "Nigeria",
    countryFlag: "ng",
    image: "",
    linkedin: "https://www.linkedin.com/in/agnes-ekong-60591a138/",
    text: "iSentry gave me industry connections that helped me land my first job. The network of mentors and peers is invaluable.",
    year: "2025",
    cohort: "2025-Q2",
    isBestInCohort: true,
  },
  {
    id: "11",
    name: "Deborah Ogunjobi",
    role: "Product Manager",
    country: "Nigeria",
    countryFlag: "ng",
    image: "",
    linkedin:
      "https://www.linkedin.com/in/deborah-ogunjobi-b1396425a",
    text: "iSentry gave me industry connections that helped me land my first job. The network of mentors and peers is invaluable.",
    year: "2025",
    cohort: "2025-Q2",
  },
  {
    id: "12",
    name: "Perela Ipiteikumoh",
    role: "QA Engineer",
    country: "Nigeria",
    countryFlag: "ng",
    image: "/interns images/IMG_0095 - Perela Ipiteikumoh.JPG",
    linkedin: "http://linkedin.com/in/perela-ipiteikumoh",
    text: "iSentry gave me industry connections that helped me land my first job. The network of mentors and peers is invaluable.",
    year: "2025",
    cohort: "2025-Q2",
  },
  {
    id: "13",
    name: "Rejoice Oluchukwu Orauno",
    role: "QA Engineer",
    country: "Nigeria",
    countryFlag: "ng",
    image: "",
    linkedin: "https://www.linkedin.com/in/rejoice-orauno-6b084a204/",
    text: "iSentry gave me industry connections that helped me land my first job. The network of mentors and peers is invaluable.",
    year: "2025",
    cohort: "2025-Q2",
  },
  {
    id: "14",
    name: "Famakinwa Esther",
    role: "QA Engineer",
    country: "Nigeria",
    countryFlag: "ng",
    image: Esther,
    linkedin: "https://www.linkedin.com/in/famakinwa-esther-35b07512a",
    text: "iSentry gave me industry connections that helped me land my first job. The network of mentors and peers is invaluable.",
    year: "2025",
    cohort: "2025-Q2",
  },
  {
    id: "15",
    name: "Praise Assam Etuk",
    role: "Social Media/Content Marketing",
    country: "Nigeria",
    countryFlag: "ng",
    image: "",
    linkedin: "https://www.linkedin.com/in/praise-assam-648185396/",
    text: "iSentry gave me industry connections that helped me land my first job. The network of mentors and peers is invaluable.",
    year: "2025",
    cohort: "2025-Q2",
  },
  {
    id: "16",
    name: "Adejayan Esther Oluwanike",
    role: "Social Media/Content Marketing",
    country: "Nigeria",
    countryFlag: "ng",
    image: Adejayan,
    linkedin: "https://www.linkedin.com/in/esther-adejayan-ab9976368",
    text: "iSentry gave me industry connections that helped me land my first job. The network of mentors and peers is invaluable.",
    year: "2025",
    cohort: "2025-Q2",
    isBestInCohort: true,
  },
  {
    id: "17",
    name: "Aishat Yusuf",
    role: "Data Analysis",
    country: "Nigeria",
    countryFlag: "ng",
    image: Aishat,
    linkedin: "https://www.linkedin.com/in/aishat-yusuf",
    text: "iSentry gave me industry connections that helped me land my first job. The network of mentors and peers is invaluable.",
    year: "2025",
    cohort: "2025-Q2",
  },
  {
    id: "18",
    name: "Aminat Bankole",
    role: "Data Analysis",
    country: "Nigeria",
    countryFlag: "ng",
    image: Aminat,
    linkedin: "http://www.linkedin.com/in/aminat-bankole-0b8071188",
    text: "iSentry gave me industry connections that helped me land my first job. The network of mentors and peers is invaluable.",
    year: "2025",
    cohort: "2025-Q2",
  },
  {
    id: "19",
    name: "Adefemi Damola",
    role: "Social Media/Content Marketing",
    country: "Nigeria",
    countryFlag: "ng",
    image: Adefemi,
    linkedin:
      "https://www.linkedin.com/in/damola-adefemi-1396112a1",
    text: "iSentry gave me industry connections that helped me land my first job. The network of mentors and peers is invaluable.",
    year: "2025",
    cohort: "2025-Q2",
  },
  {
    id: "20",
    name: "Bobbai Thomas",
    role: "Data Analysis",
    country: "Nigeria",
    countryFlag: "ng",
    image: "",
    linkedin: "https://www.linkedin.com/in/bobbai-thomas/",
    text: "iSentry gave me industry connections that helped me land my first job. The network of mentors and peers is invaluable.",
    year: "2025",
    cohort: "2025-Q2",
  },
  {
    id: "21",
    name: "Chioma, Favour Paul-Chike",
    role: "Social Media/Content Marketing",
    country: "Nigeria",
    countryFlag: "ng",
    image: chioma,
    linkedin: "https://www.linkedin.com/in/chioma-favour-paul-chike-bb23ba363/",
    text: "iSentry gave me industry connections that helped me land my first job. The network of mentors and peers is invaluable.",
    year: "2025",
    cohort: "2025-Q2",
    isBestInCohort: true,
  },
  {
    id: "22",
    name: "George Bassey",
    role: "Frontend Developer",
    country: "Nigeria",
    countryFlag: "ng",
    image: "",
    linkedin: "https://www.linkedin.com/in/george-bassey-6a0a57239/",
    text: "iSentry gave me industry connections that helped me land my first job. The network of mentors and peers is invaluable.",
    year: "2025",
    cohort: "2025-Q2",
    isBestInCohort: true,
  },
  {
    id: "23",
    name: "Mercy Ochieng ",
    role: "Frontend Developer",
    country: "Kenya",
    countryFlag: "ke",
    image: "",
    linkedin: "",
    text: "iSentry gave me industry connections that helped me land my first job. The network of mentors and peers is invaluable.",
    year: "2025",
    cohort: "2025-Q2",
  },
  {
    id: "24",
    name: "Mattia Lavai",
    role: "Frontend Developer",
    country: "Sierra Leon",
    countryFlag: "sl",
    image: "",
    linkedin: "https://www.linkedin.com/in/lavaimattia877",
    text: "iSentry gave me industry connections that helped me land my first job. The network of mentors and peers is invaluable.",
    year: "2025",
    cohort: "2025-Q2",
  },
  {
    id: "25",
    name: "Sifan Yemane Guteta",
    role: "Frontend Developer",
    country: "Ethiopia",
    countryFlag: "et",
    image: Sifan,
    linkedin: "https://www.linkedin.com/in/sifan-yemane-b34880384/",
    text: "iSentry gave me industry connections that helped me land my first job. The network of mentors and peers is invaluable.",
    year: "2025",
    cohort: "2025-Q2",
    isBestInCohort: true,
  },
  {
    id: "26",
    name: "Kolade Faith Aramide ",
    role: "Frontend Developer",
    country: "Nigeria",
    countryFlag: "ng",
    image: Faith,
    linkedin:
      "https://www.linkedin.com/in/kolade-faith-aramide-15ba1637a",
    text: "iSentry gave me industry connections that helped me land my first job. The network of mentors and peers is invaluable.",
    year: "2025",
    cohort: "2025-Q2",
  },
  {
    id: "27",
    name: "Oshunkeye Oluwatoyosi John",
    role: "QA Engineer",
    country: "Nigeria",
    countryFlag: "ng",
    image: "",
    linkedin: "",
    text: "iSentry gave me industry connections that helped me land my first job. The network of mentors and peers is invaluable.",
    year: "2025",
    cohort: "2025-Q2",
  },
  {
    id: "28",
    name: "Olowolayemo Olawale Bernard ",
    role: "QA Engineer",
    country: "Nigeria",
    countryFlag: "ng",
    image: Olawale,
    linkedin:
      "https://www.linkedin.com/in/olowolayemo-olawale-a635a923b?utm_source=share&utm_campaign=share_via&utm_content=profile&utm_medium=android_app",
    text: "iSentry gave me industry connections that helped me land my first job. The network of mentors and peers is invaluable.",
    year: "2025",
    cohort: "2025-Q2",
    isBestInCohort: true,
  },
  {
    id: "29",
    name: "Emmanuel Adeleke",
    role: "QA Engineer",
    country: "Nigeria",
    countryFlag: "ng",
    image: Emmanuel,
    linkedin: "https://www.linkedin.com/in/emmanuel-adeleke-5b933b370",
    text: "iSentry gave me industry connections that helped me land my first job. The network of mentors and peers is invaluable.",
    year: "2025",
    cohort: "2025-Q2",
    isBestInCohort: true,
  },
  {
    id: "30",
    name: "Samuel Dania",
    role: "QA Engineer",
    country: "Nigeria",
    countryFlag: "ng",
    image: SAMUEL,
    linkedin: "http://linkedin.com/in/samueldania",
    text: "iSentry gave me industry connections that helped me land my first job. The network of mentors and peers is invaluable.",
    year: "2025",
    cohort: "2025-Q2",
  },
  {
    id: "31",
    name: "Ogunsuada Joseph Anuoluwapo",
    role: "QA Engineer",
    country: "Nigeria",
    countryFlag: "ng",
    image: "",
    linkedin: "https://www.linkedin.com/in/joseph-ogunsuada-236aa9259/",
    text: "iSentry gave me industry connections that helped me land my first job. The network of mentors and peers is invaluable.",
    year: "2025",
    cohort: "2025-Q2",
  },
  {
    id: "32",
    name: "Olaleye Ifeoluwa",
    role: "QA Engineer",
    country: "Nigeria",
    countryFlag: "ng",
    image: Olayele,
    linkedin: "https://www.linkedin.com/in/olaife84/",
    text: "iSentry gave me industry connections that helped me land my first job. The network of mentors and peers is invaluable.",
    year: "2025",
    cohort: "2025-Q2",
  },
  {
    id: "33",
    name: "Waheed Sodiq Demola ",
    role: "QA Engineer",
    country: "Nigeria",
    countryFlag: "ng",
    image: "",
    linkedin:
      "https://www.linkedin.com/in/sodiq-waheed?utm_source=share&utm_campaign=share_via&utm_content=profile&utm_medium=android_app",
    text: "iSentry gave me industry connections that helped me land my first job. The network of mentors and peers is invaluable.",
    year: "2025",
    cohort: "2025-Q2",
  },
  {
    id: "34",
    name: "Nyore-Lagos Evelyn Enakeno",
    role: "QA Engineer",
    country: "Nigeria",
    countryFlag: "ng",
    image: Evelyn,
    linkedin: "http://linkedin.com/in/evelyn-nyore-lagos-87483616b",
    text: "iSentry gave me industry connections that helped me land my first job. The network of mentors and peers is invaluable.",
    year: "2025",
    cohort: "2025-Q2",
  },
  {
    id: "35",
    name: "Israel Emmanuel Chukwufunaya",
    role: "QA Engineer",
    country: "Nigeria",
    countryFlag: "ng",
    image: "",
    linkedin: "",
    text: "iSentry gave me industry connections that helped me land my first job. The network of mentors and peers is invaluable.",
    year: "2025",
    cohort: "2025-Q2",
  },
  {
    id: "36",
    name: "Mutana Kingsley",
    role: "QA Engineer",
    country: "Nigeria",
    countryFlag: "ng",
    image: "",
    linkedin: "https://www.linkedin.com/in/kingsley-mutana-b92131269",
    text: "iSentry gave me industry connections that helped me land my first job. The network of mentors and peers is invaluable.",
    year: "2025",
    cohort: "2025-Q2",
  },
  {
    id: "37",
    name: "Theresa Ogwuche ",
    role: "QA Engineer",
    country: "Nigeria",
    countryFlag: "ng",
    image: "",
    linkedin: "",
    text: "iSentry gave me industry connections that helped me land my first job. The network of mentors and peers is invaluable.",
    year: "2025",
    cohort: "2025-Q2",
  },
  {
    id: "38",
    name: "Oyedun Oluwatosin",
    role: "QA Engineer",
    country: "Nigeria",
    countryFlag: "ng",
    image: Tosin,
    linkedin: "http://linkedin.com/in/oluwatosin-oyedun-66867a1b1",
    text: "iSentry gave me industry connections that helped me land my first job. The network of mentors and peers is invaluable.",
    year: "2025",
    cohort: "2025-Q2",
  },
  {
    id: "39",
    name: "Etietop Ekong",
    role: "Product Manager",
    country: "Nigeria",
    countryFlag: "ng",
    image: "",
    linkedin: "",
    text: "iSentry gave me industry connections that helped me land my first job. The network of mentors and peers is invaluable.",
    year: "2025",
    cohort: "2025-Q2",
  },
  {
    id: "40",
    name: "Adeola Omomowo",
    role: "Frontend Developer",
    country: "Nigeria",
    countryFlag: "ng",
    image: Adeola,
    linkedin: "https://www.linkedin.com/in/adeola-omomowo",
    text: "iSentry gave me industry connections that helped me land my first job. The network of mentors and peers is invaluable.",
    year: "2025",
    cohort: "2025-Q2",
    isBestInCohort: true,
  },
  {
    id: "41",
    name: "Nameti Hezekiah Charlie",
    role: "QA Engineer",
    country: "Nigeria",
    countryFlag: "ng",
    image: "",
    linkedin: "https://www.linkedin.com/in/nameti-charlie-6a27692b5/",
    text: "iSentry gave me industry connections that helped me land my first job. The network of mentors and peers is invaluable.",
    year: "2025",
    cohort: "2025-Q2",
    isBestInCohort: true,
  },
  {
    id: "42",
    name: "Saidu Musa Auna",
    role: "QA Engineer",
    country: "Nigeria",
    countryFlag: "ng",
    image: Musa,
    linkedin: "https://www.linkedin.com/in/saidu-musa-auna-379998186/",
    text: "iSentry gave me industry connections that helped me land my first job. The network of mentors and peers is invaluable.",
    year: "2025",
    cohort: "2025-Q2",
  },
  {
    id: "43",
    name: "John Ibhaluobe",
    role: "Front-end Developer",
    country: "Nigeria",
    countryFlag: "ng",
    image: John,
    linkedin:
      "https://www.linkedin.com/in/ibhaluobe-eichie-650564304?utm_source=share&utm_campaign=share_via&utm_content=profile&utm_medium=android_app",
    text: "iSentry gave me industry connections that helped me land my first job. The network of mentors and peers is invaluable.",
    year: "2025",
    cohort: "2025-Q2",
  },
  {
    id: "44",
    name: "Ruth Abuh",
    role: "Social Media/Content Marketing",
    country: "Nigeria",
    countryFlag: "ng",
    image: "/interns images/IMG_1080~2 - Ruth Abuh.JPG",
    linkedin: "https://www.linkedin.com/in/ruth-abuh-4b935935b?",
    text: "iSentry gave me industry connections that helped me land my first job. The network of mentors and peers is invaluable.",
    year: "2025",
    cohort: "2025-Q2",
  },
  {
    id: "45",
    name: "Nwokolobia Onyedikachuwku Divine",
    role: "Social Media/Content Marketing",
    country: "Nigeria",
    countryFlag: "ng",
    image: "",
    linkedin:
      "https://www.linkedin.com/in/divine-nwokolobia-889717375?utm_source=share&utm_campaign=share_via&utm_content=profile&utm_medium=android_app",
    text: "iSentry gave me industry connections that helped me land my first job. The network of mentors and peers is invaluable.",
    year: "2025",
    cohort: "2025-Q2",
  },
];

export const mentors: Mentor[] = [
  {
    id: "1",
    name: "Idorenyin Williams",
    role: "Founder & Lead Mentor",
    bio: "Idorenyin founded iSentry Technologies to bridge the gap between academic learning and industry demands. He specializes in Frontend Engineering (React/TypeScript) and is passionate about building Africa's digital future.",
    image: williams,
    linkedin: "https://www.linkedin.com/in/idorenyin-williams",
  },
   {
    id: "3",
    name: "Akanimo Ekong",
    role: "Mobile Engineer & Socials/Creative Lead",
    bio: "A Mobile Engineer and Creative Director who drives iSentry's community engagement. Akanimo combines technical knowledge with creative strategy to manage the brand's digital presence, having successfully boosted engagement by over 300%.",
    image: akanimo,
    linkedin: "https://www.linkedin.com/in/akanimoekong",
  },
  {
    id: "2",
    name: "Timilehin Abegunde",
    role: "Frontend Mentor",
    bio: "Frontend Engineer specializing in building scalable SaaS and Web3 applications. Timilehin brings deep expertise in the React ecosystem (Next.js, TypeScript) and helps interns master the art of converting complex designs into pixel-perfect, performant code.",
    image: timi,
    linkedin: "https://www.linkedin.com/in/timilehin-abegunde",
  },
  {
    id: "5",
    name: "Oluwaseun Bamgbade",
    role: "Program Coordinator",
    bio: "The operational backbone of the internship. Oluwaseun oversees the daily running of the program, ensuring that mentors and interns remain aligned. He manages schedules, resource allocation, and progress tracking to guarantee a smooth learning experience for every cohort.",
    image: seun,
    linkedin: "https://www.linkedin.com/in/oluwaseun-bamgbade-45657b19a",
  },

  {
    id: "4",
    name: "Wangui Njoroge",
    role: "Product Design & Frontend",
    bio: "The bridge between design and code. Wangui specializes in UI/UX-focused engineering, ensuring that applications are not just functional but intuitive. She mentors interns on design systems, accessibility, and the 'developer-designer' handoff workflow.",
    image: wangui,
    linkedin: "https://www.linkedin.com/in/wangui-njoroge-639378181",
  },

];

export const blogPosts: BlogPost[] = [
  {
    id: "1",
    title: "Announcing Our 2025 Cohort: Applications Now Open",
    excerpt:
      "We are thrilled to announce that applications for the 2025 iSentry Internship cohort are now open. Join Africa's most practical tech internship program.",
    thumbnail:
      "https://images.pexels.com/photos/3184291/pexels-photo-3184291.jpeg?auto=compress&cs=tinysrgb&w=800",
    date: "2025-01-15",
    author: "Idorenyin Williams",
    slug: "announcing-2025-cohort",
    content: "Full blog post content here...",
  },
  {
    id: "2",
    title: "Success Stories: How Our Interns Landed Their Dream Jobs",
    excerpt:
      "Hear from our alumni about how the iSentry Internship program helped them secure positions at leading tech companies across Africa.",
    thumbnail:
      "https://images.pexels.com/photos/3184357/pexels-photo-3184357.jpeg?auto=compress&cs=tinysrgb&w=800",
    date: "2024-12-20",
    author: "Chioma Adewale",
    slug: "success-stories-dream-jobs",
    content: "Full blog post content here...",
  },
  {
    id: "3",
    title: "Building Real Products: The iSentry Approach",
    excerpt:
      "Learn about our unique methodology that puts interns on real projects from day one, fostering practical skills and professional growth.",
    thumbnail:
      "https://images.pexels.com/photos/3184360/pexels-photo-3184360.jpeg?auto=compress&cs=tinysrgb&w=800",
    date: "2024-11-10",
    author: "Emmanuel Nduka",
    slug: "building-real-products",
    content: "Full blog post content here...",
  },
];

export const metrics: Metric[] = [
  { id: "1", label: "Interns Trained", value: 50, suffix: "+" },
  { id: "2", label: "Countries Represented", value: 5, suffix: "" },
  { id: "3", label: "Real-World Projects", value: 5, suffix: "+" },
  { id: "4", label: "Placement Rate", value: 50, suffix: "%" },
];

export const cohorts: Cohort[] = [
  {
    id: "1",
    year: "2024",
    name: "2024 Q1 Cohort",
    description:
      "Our inaugural cohort bringing together 12 talented developers from across Africa.",
    startDate: "2024-01-15",
    endDate: "2024-04-15",
    internCount: 12,
  },
  {
    id: "2",
    year: "2025",
    name: "2025 Q2 Cohort",
    description:
      "Second cohort with 12 exceptional interns working on diverse projects.",
    startDate: "2025-09-05",
    endDate: "2025-12-20",
    internCount: 12,
  },
];

export const projects: InternProject[] = [
  {
    id: "1",
    title: "Porker hut",
    description:
      "A comprehensive job portal connecting African tech talent with opportunities across the continent.",
    image:
      "https://images.pexels.com/photos/3945683/pexels-photo-3945683.jpeg?auto=compress&cs=tinysrgb&w=800",
    technologies: ["React", "Node.js", "PostgreSQL", "AWS"],
    cohort: "2024-Q1",
    internCount: 4,
    link: "#",
  },
  {
    id: "2",
    title: "Cake App",
    description:
      "Advanced analytics platform for tracking business metrics with real-time data visualization.",
    image:
      "https://images.pexels.com/photos/3807517/pexels-photo-3807517.jpeg?auto=compress&cs=tinysrgb&w=800",
    technologies: ["Next.js", "TypeScript", "Supabase", "Chart.js"],
    cohort: "2024-Q1",
    internCount: 3,
    link: "https://goldies-frontend-v3.vercel.app/",
  },
  {
    id: "3",
    title: "TeamIQ",
    description:
      "An innovative platform making tech education accessible to students across Africa via mobile.",
    image:
      "https://images.pexels.com/photos/3769021/pexels-photo-3769021.jpeg?auto=compress&cs=tinysrgb&w=800",
    technologies: ["React Native", "Firebase", "Node.js"],
    cohort: "2025-Q2",
    internCount: 3,
    link: "#",
  },
  // {
  //   id: "4",
  //   title: "Community Forum & Marketplace",
  //   description:
  //     "Thriving digital community platform enabling tech professionals to connect and collaborate.",
  //   image:
  //     "https://images.pexels.com/photos/3182812/pexels-photo-3182812.jpeg?auto=compress&cs=tinysrgb&w=800",
  //   technologies: ["Vue.js", "Python", "MongoDB", "Redis"],
  //   cohort: "2024-Q2",
  //   internCount: 2,
  //   link: "#",
  // },
];

export const partners: Partner[] = [
  {
    id: "1",
    name: "iSentry Technologies",
    logo: BSY,
    category: "sponsor",
    website: "https://isentrytechnologies.com/",
  },
  // {
  //   id: "2",
  //   name: "AWS",
  //   logo: "https://images.pexels.com/photos/3945683/pexels-photo-3945683.jpeg?auto=compress&cs=tinysrgb&w=200",
  //   category: "technology",
  //   website: "#",
  // },
  // {
  //   id: "3",
  //   name: "GitHub",
  //   logo: "https://images.pexels.com/photos/270348/pexels-photo-270348.jpeg?auto=compress&cs=tinysrgb&w=200",
  //   category: "technology",
  //   website: "#",
  // },
  // {
  //   id: "4",
  //   name: "Tech Startups Africa",
  //   logo: "https://images.pexels.com/photos/3182812/pexels-photo-3182812.jpeg?auto=compress&cs=tinysrgb&w=200",
  //   category: "hiring",
  //   website: "#",
  // },
  {
    id: "5",
    name: "Beyond Service Year (BSY)",
    logo: BSY,
    category: "community",
    website: "#",
  },
];

// export const resources: Resource[] = [
//   {
//     id: "1",
//     title: "React Documentation",
//     description:
//       "Official React documentation and guides for building modern web applications.",
//     category: "documentation",
//     link: "https://react.dev",
//   },
//   {
//     id: "2",
//     title: "Node.js Best Practices",
//     description:
//       "Comprehensive guide to writing scalable backend applications with Node.js.",
//     category: "learning",
//     link: "https://nodejs.org/en/learn/getting-started/security-best-practices",
//   },
//   {
//     id: "3",
//     title: "System Design Fundamentals",
//     description: "Learn the principles of designing large-scale systems.",
//     category: "learning",
//     link: "https://www.systemdesignhandbook.com/guides/system-design-fundamentals/",
//   },
//   {
//     id: "4",
//     title: "Prompt Engineering Guide",
//     description: "Essential patterns for designing efficient database schemas.",
//     category: "documentation",
//     link: "https://cloud.google.com/discover/what-is-prompt-engineering",
//   },
//   {
//     id: "5",
//     title: "Git & GitHub for Beginners",
//     description:
//       "Master Git workflows and best practices for team collaboration.",
//     category: "tools",
//     link: "https://www.freecodecamp.org/news/learn-how-to-use-git-and-github-a-beginner-friendly-handbook/",
//   },
//   {
//     id: "6",
//     title: "Developer Community Discord",
//     description: "Join our thriving Discord community of African developers.",
//     category: "community",
//     link: "#",
//   },
//   {
//     id: "7",
//     title: "Developer Community Discord",
//     description: "Join our thriving Discord community of African developers.",
//     category: "community",
//     link: "#",
//   },
//   {
//     id: "8",
//     title: "Developer Community Discord",
//     description: "Join our thriving Discord community of African developers.",
//     category: "community",
//     link: "#",
//   },
// ];



// import { Resource } from "@/lib/types";

export const resources: Resource[] = [
  // --- CORE FRAMEWORKS & LANGUAGES ---
  {
    id: "1",
    title: "React Documentation",
    description: "The official bible for React. Essential for mastering components, hooks, and state management.",
    category: "documentation",
    link: "https://react.dev",
  },
  {
    id: "nextjs-learn",
    title: "Next.js: The Official Course",
    description: "Master App Router, Server Actions, and full-stack development. The backbone of modern web apps.",
    category: "learning",
    link: "https://nextjs.org/learn",
  },
  {
    id: "typescript-docs",
    title: "TypeScript Handbook",
    description: "Essential for modern development. Learn how to write type-safe code to prevent bugs before they happen.",
    category: "documentation",
    link: "https://www.typescriptlang.org/docs/",
  },
  {
    id: "mdn-web",
    title: "MDN Web Docs",
    description: "The encyclopaedia of web development. The most trusted resource for HTML, CSS, and JavaScript references.",
    category: "documentation",
    link: "https://developer.mozilla.org/en-US/",
  },

  // --- BACKEND & DATABASES ---
  {
    id: "2",
    title: "Node.js Best Practices",
    description: "A comprehensive guide to writing scalable, secure, and production-ready backend applications.",
    category: "learning",
    link: "https://github.com/goldbergyoni/nodebestpractices",
  },
  {
    id: "fastapi-docs",
    title: "FastAPI Documentation",
    description: "The go-to resource for our Python backend track. Build high-performance APIs with automatic docs.",
    category: "documentation",
    link: "https://fastapi.tiangolo.com/",
  },
  {
    id: "mongodb-uni",
    title: "MongoDB University",
    description: "Free courses to master NoSQL databases. Crucial for the 'M' in our MERN stack projects.",
    category: "learning",
    link: "https://learn.mongodb.com/",
  },
  {
    id: "prisma-orm",
    title: "Prisma ORM",
    description: "Next-generation Node.js and TypeScript ORM. Makes working with databases intuitive and type-safe.",
    category: "tools",
    link: "https://www.prisma.io/docs",
  },

  // --- DEVOPS & INFRASTRUCTURE ---
  {
    id: "docker-guide",
    title: "Docker for Beginners",
    description: "Understand containerization. Package your applications to run consistently across any environment.",
    category: "learning",
    link: "https://docker-curriculum.com/",
  },
  {
    id: "aws-skillbuilder",
    title: "AWS Cloud Essentials",
    description: "Official training for Amazon Web Services. Learn how to deploy, scale, and manage cloud infrastructure.",
    category: "learning",
    link: "https://explore.skillbuilder.aws/",
  },

  // --- TOOLS & WORKFLOW ---
  {
    id: "5",
    title: "Git & GitHub Workflow",
    description: "Master branching strategies, Pull Requests, and code reviews. This is how we collaborate as a team.",
    category: "tools",
    link: "https://docs.github.com/en/get-started/using-git/about-git",
  },
  {
    id: "postman-platform",
    title: "Postman API Platform",
    description: "The standard tool for testing APIs. Debug your endpoints before connecting them to the frontend.",
    category: "tools",
    link: "https://www.postman.com/",
  },
  {
    id: "figma-dev",
    title: "Figma for Developers",
    description: "Bridge the gap between design and code. Inspect files, export assets, and implement pixel-perfect UIs.",
    category: "tools",
    link: "https://www.figma.com/dev-mode/",
  },
  {
    id: "vscode-tricks",
    title: "VS Code Power User",
    description: "Master the editor. Shortcuts, extensions, and debugging tricks to double your coding speed.",
    category: "tools",
    link: "https://code.visualstudio.com/docs/getstarted/tips-and-tricks",
  },

  // --- CAREER & SOFT SKILLS ---
  {
    id: "neetcode",
    title: "NeetCode.io",
    description: "The best resource for practicing Data Structures & Algorithms (DSA) for technical interviews.",
    category: "learning",
    link: "https://neetcode.io/",
  },
  {
    id: "roadmap-sh",
    title: "Developer Roadmaps",
    description: "Visual roadmaps showing the skills you need to learn for Frontend, Backend, and DevOps roles.",
    category: "learning",
    link: "https://roadmap.sh/",
  },
  {
    id: "3",
    title: "System Design Fundamentals",
    description: "Learn the principles of designing large-scale systems. Key for moving from Junior to Senior engineering.",
    category: "learning",
    link: "https://www.systemdesignhandbook.com/",
  },

  // --- COMMUNITY ---
  {
    id: "frontend-mentor",
    title: "Frontend Mentor",
    description: "Sharpen your CSS/JS skills by building real-world projects with professional designs.",
    category: "community",
    link: "https://www.frontendmentor.io/",
  },
  {
    id: "dev-to",
    title: "DEV Community",
    description: "A constructive and inclusive social network for software developers. Great for reading and writing articles.",
    category: "community",
    link: "https://dev.to/",
  },
  {
    id: "6",
    title: "iSentry Community Discord",
    description: "Connect with fellow interns, mentors, and alumni. Share wins, debug code, and network.",
    category: "community",
    link: "#",
  },
];
